[package]
name = "change_eth_signer"
type = "bin"
authors = [""]
compiler_version = "0.17.0"

[dependencies]
bjj = { tag = "v0.1.0", git = "https://github.com/jat9292/noir-elgamal" }
# add ecrecover lib