[package]
name = "withdraw_4337"
type = "bin"
authors = [""]
compiler_version = ">=0.19.2"

[dependencies]
bjj = { tag = "v0.2.0", git = "https://github.com/Bank-of-JubJub/noir-elgamal" }
utils = { path="../utils" }